### ISSUE TITLE
[Feature] AttachmentBuilder

### ISSUE THREAD

**Issue by mezotv** [fb-sean/interactions.js#8]
Add an attachment builder to turn buffers into images and sent them like the one in discord.js

**Comment by fb-sean** [comment]
This requires forms responses Ijs currently dont support form responses because of a internal issue.

**Comment by mezotv** [comment]
> This requires forms responses Ijs currently dont support form responses because of a internal issue. 

Oh alright hope that gets fixed in the ts rewrite.

**Comment by fb-sean** [comment]
"files" is a valid property we dont have a attachment builder bcs not needed
